### ISSUE TITLE
No data other than Position and Last Update

### ISSUE THREAD

**Issue by Th3H0ff** [kvj/hass_Mtastic_MQTT#12]
Greetings
I came across this cool project and jumped right on it since my mesh is growing fast and setting all nodes up in HA is quite a chore. Setup seems quite straight forward, I run an EMQX cluster for various other projects and HA has a connection to this cluster already. However I've set up three different Meshtastic nodes and none of them populate battery, enviromental stuff or anything else. Just Position and Last Update.
I use a private primary channel for all my telemetry and I've used that key from the app but it has no effect. I also use version 2.5.7 or above on all my Meshtastic nodes.
The diagnostic log from the integration gives
2024-11-25 20:36:20.204 WARNING (MainThread) [homeassistant.components.mqtt.sensor] Invalid state message 'unknown' from 'msh/EU_868/2/json/HoffChannel/!7c5cb244'
2024-11-25 20:36:20.204 WARNING (MainThread) [homeassistant.components.mqtt.sensor] Invalid state message 'unknown' from 'msh/EU_868/2/json/HoffChannel/!7c5cb244'
2024-11-25 20:36:20.206 WARNING (MainThread) [homeassistant.components.mqtt.sensor] Invalid state message 'unknown' from 'msh/EU_868/2/json/HoffChannel/!7c5cb244'

**Comment by maylay** [comment]
It looks like you're using the json topic, this integration uses the protobuf topic. You may want to try `msh/EU_868/2/e/HoffChannel/!7c5cb244` instead. Also I believe you need to go into the integration and enable any extra entities that you want to keep track of.

**Comment by Th3H0ff** [comment]
Correction. That is the channel I'm using for the config in HA. msh/EU_868/2/e/HoffChannel/!7c5cb244 is the value entered.

**Comment by Th3H0ff** [comment]
I've fiddled with different combinations, for troubleshooting. Channel key, no channel key, no JSON MQTT on the node, add a new node. So far same result. Last update and position are the only value that changes and all other are disabled.

**Comment by kvj** [comment]
Do you see a protobuf (binary) data coming to your MQTT server on that topic(s)? Using MQTT Explorer or something

**Comment by Th3H0ff** [comment]
Yes, there is protobuf data coming to MQTT. I haven't made any attempt at reading it though. Is there some version requirement to Meshtastic? I think I read somewhere that the protobuf changed somewhere along the line.
![image](https://github.com/user-attachments/assets/aa922483-6e41-4d5d-b24d-d9e0f08cfc78)

I also added Meshtastic to my node-red and there I'm able to decode the protobufs. Going through node-red seems like unnecessary steps though. 
![image](https://github.com/user-attachments/assets/104e00e3-356f-4c0d-a60c-c51696e8ecac)

**Comment by kvj** [comment]
Should work then (works for me). Have you tried enabling debug logs for the integration? It dumps all types of protobuf messages it receives

**Comment by Th3H0ff** [comment]
The debug log grows quickly, I've got alot going on with my Home Assistant.
I've found some of these
ReceiveMessage(topic='msh/EU_868/2/e/HoffChannel/!7c5cb244', payload=b'\nL\r\xd0}\x14f\x15\xff\xff\xff\xff""\x08C\x12\x1c\r\x9c\xda\x0f\x00\x12\x15\x08\x18\x15\xdd$^@\x1d\xe1z\xbc@%e\xceQ@(\x9c\xb5?H\x015\xae\xe8\xc5A=o\x85IgE\x00\x00\xa8@H\x03`\xa0\xff\xff\xff\xff\xff\xff\xff\xff\x01x\x03\x12\x0bHoffChannel\x1a\t!7c5cb244', qos=0, retain=0, subscribed_topic='msh/EU_868/2/e/HoffChannel/!7c5cb244', timestamp=741727.533981842)
2024-11-29 11:12:17.504 DEBUG (MainThread) [custom_components.mtastic_mqtt.coordinator] _async_on_pb_message(): parsed packet {
  from: 1712618960
  to: 4294967295
  decoded {
    portnum: TELEMETRY_APP
    payload: "\r\234\332\017\000\022\025\010\030\025\335$^@\035\341z\274@%e\316Q@(\234\265?"
    bitfield: 1
  }
  id: 1103489198
  rx_time: 1732871535
  rx_snr: 5.25
  hop_limit: 3
  rx_rssi: -96
  hop_start: 3
}
channel_id: "HoffChannel"
gateway_id: "!7c5cb244"

2024-11-29 11:12:17.504 DEBUG (MainThread) [custom_components.mtastic_mqtt.proto] convert_packet_to_json(): proto = time: 1039004
device_metrics {
  battery_level: 24
  voltage: 3.471
  channel_utilization: 5.89
  air_util_tx: 3.27822232
  uptime_seconds: 1039004
}

**Comment by kvj** [comment]
you can only filter messages from `custom_components.mtastic_mqtt` if it helps. 

the messages above look as expected, it seems that data is coming

**Comment by Th3H0ff** [comment]
I agree. Looks like Home Assistant is getting something. I have no clue how to proceed or which information to give you. I run HA as a docker instance, version 2024.11.3.
Damn. It would have saved me alot of time if this integration worked.

**Comment by kvj** [comment]
I have to ask :smile: 
have you enabled the entities you're looking for? By default they're all disabled

**Comment by Th3H0ff** [comment]
Oh my God! No I only assumed they would enable themselves once data was processed.
I went and enabled them all and, well, there it is.
![image](https://github.com/user-attachments/assets/1ca47271-9ec0-4ce2-a229-72a19768130d)
