### ISSUE TITLE
Editing will freeze HA

### ISSUE THREAD

**Issue by brebtatv** [kvj/hass_Mtastic_MQTT#8]
It causes HA to freeze when trying to change settings.

**Comment by kvj** [comment]
yeah, I've also recently realized that. I will take a look

**Comment by accik** [comment]
Can confirm with HA version 2024.9.2

**Comment by brebtatv** [comment]
The error is still present

Core
2024.10.4
Supervisor
2024.10.3
Operating System
13.2
Front end
20241002.4
